# Implement matmul in 3 ways

In [36]:
import torch

In [37]:
matrix_a_dimension = (3,4)
matrix_b_dimension = (4,5)

matrix_a = torch.randn(matrix_a_dimension)
matrix_b = torch.randn(matrix_b_dimension)
expected_output = matrix_a @ matrix_b
print(expected_output)

tensor([[ 5.5901, -0.1768, -4.3301, -3.2070,  1.0424],
        [-1.5086,  1.9594, -1.5368,  1.0118, -1.9976],
        [ 0.7761,  0.8954, -1.3579, -0.4201, -0.3886]])


In [38]:
# nested loops based matmul
rows_a = matrix_a_dimension[0]
inner_dimension = matrix_a_dimension[1]
column_b = matrix_b_dimension[1]
result = torch.zeros(rows_a, column_b)

for row_a in range(rows_a):
    for col_b in range(column_b):
        for i in range(inner_dimension):
            result[row_a][col_b]+=matrix_a[row_a][i] * matrix_b[i][col_b]

print(result)
print(f'\nDoes tensor matmul matches with loop impl: {torch.allclose(expected_output, result)}')

tensor([[ 5.5901, -0.1768, -4.3301, -3.2070,  1.0424],
        [-1.5086,  1.9594, -1.5368,  1.0118, -1.9976],
        [ 0.7761,  0.8954, -1.3579, -0.4201, -0.3886]])

Does tensor matmul matches with loop impl: True


In [39]:
# dot product based matmul
dot_product_result = torch.zeros(rows_a, column_b)
for row_a in range(rows_a):
    for col_b in range(column_b):
        dot_product_result[row_a][col_b] = torch.dot(matrix_a[row_a, :], matrix_b[:, col_b])
print(dot_product_result)
print(f'\nDoes tensor matmul matches with dot product based impl: {torch.allclose(expected_output, result)}')

tensor([[ 5.5901, -0.1768, -4.3301, -3.2070,  1.0424],
        [-1.5086,  1.9594, -1.5368,  1.0118, -1.9976],
        [ 0.7761,  0.8954, -1.3579, -0.4201, -0.3886]])

Does tensor matmul matches with dot product based impl: True


In [40]:
# Weighted sum: column col_b of the output = sum over i of matrix_b[i, col_b] * (column i of matrix_a)
weighted_sum_result = torch.zeros(rows_a, column_b)
for col_b in range(column_b):
    for i in range(inner_dimension):
        weighted_sum_result[:, col_b] += matrix_b[i, col_b] * matrix_a[:, i]
print(weighted_sum_result)
print(f'\nDoes tensor matmul matches with weighted sum based impl: {torch.allclose(expected_output, weighted_sum_result)}')

tensor([[ 5.5901, -0.1768, -4.3301, -3.2070,  1.0424],
        [-1.5086,  1.9594, -1.5368,  1.0118, -1.9976],
        [ 0.7761,  0.8954, -1.3579, -0.4201, -0.3886]])

Does tensor matmul matches with weighted sum based impl: True
